# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47e4b8fe1e0479020c31b1ec463da2652c00a035345ea081f335771b4f103b2c3906c0a16335e2b317e98e826b5e3b0e3de9ab90df7299b1ea8775cc7c8c4ce8
  s3_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  s3_secret: <%= ENV["S3_SECRET"] %>
  s3_bucket: localpic
  s3_region: eu-west-1
test:
  secret_key_base: 27c1590c6d56ec9111307daf997c967749f8b7ec545e7dfd61990bb529abe1b8a4271785c7e3f2d0c0ac776475cf2d2c1067e60f1ff1fa18900c6bf8ff21e969
  s3_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  s3_secret: <%= ENV["S3_SECRET"] %>
  s3_bucket: localpic
  s3_region: eu-west-1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_access_key_id: <%= ENV["S3_ACCESS_KEY_ID"] %>
  s3_secret: <%= ENV["S3_SECRET"] %>
  s3_bucket: localpic
  s3_region: eu-west-1
